name: practice-ci-cd
on:
  push:
    branches:
      - main
jobs:
  name: test
    runs-on: macos-latest
    steps:
      - run: |
        git clone git@github.com:langedoc/github-actions-masterclass.git
        ls -la